"""Initial DB from csvs

Revision ID: 530da07dbf26
Revises: 
Create Date: 2022-12-21 16:42:35.260411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530da07dbf26'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('fleet', sa.String(), nullable=True),
    sa.Column('equipment_id', sa.String(), nullable=True),
    sa.Column('equipment_status', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_removed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=True),
    sa.Column('sighting_date', sa.DateTime(), nullable=True),
    sa.Column('sighting_event_code', sa.Integer(), nullable=True),
    sa.Column('reporting_railroad_scac', sa.String(), nullable=True),
    sa.Column('posting_date', sa.DateTime(), nullable=True),
    sa.Column('from_mark_id', sa.String(), nullable=True),
    sa.Column('load_empty_status', sa.String(), nullable=True),
    sa.Column('sighting_claim_code', sa.String(), nullable=True),
    sa.Column('sighting_event_code_text', sa.String(), nullable=True),
    sa.Column('train_id', sa.String(), nullable=True),
    sa.Column('train_alpha_code', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('waybill_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('city_long', sa.String(), nullable=True),
    sa.Column('station', sa.String(), nullable=True),
    sa.Column('fsac', sa.String(), nullable=True),
    sa.Column('scac', sa.String(), nullable=True),
    sa.Column('splc', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waybills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=True),
    sa.Column('waybill_date', sa.DateTime(), nullable=True),
    sa.Column('waybill_number', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('billing_road_mark_name', sa.String(), nullable=True),
    sa.Column('waybill_source_code', sa.String(), nullable=True),
    sa.Column('load_empty_status', sa.String(), nullable=True),
    sa.Column('origin_mark_name', sa.String(), nullable=True),
    sa.Column('destination_mark_name', sa.String(), nullable=True),
    sa.Column('sending_road_mark', sa.String(), nullable=True),
    sa.Column('bill_of_lading_number', sa.String(), nullable=True),
    sa.Column('bill_of_lading_date', sa.DateTime(), nullable=True),
    sa.Column('equipment_weight', sa.String(), nullable=True),
    sa.Column('tare_weight', sa.String(), nullable=True),
    sa.Column('allowable_weight', sa.String(), nullable=True),
    sa.Column('dunnage_weight', sa.String(), nullable=True),
    sa.Column('equipment_weight_code', sa.String(), nullable=True),
    sa.Column('commodity_code', sa.Integer(), nullable=True),
    sa.Column('commodity_description', sa.String(), nullable=True),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('routes', sa.JSON(), nullable=True),
    sa.Column('parties', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waybills')
    op.drop_table('locations')
    op.drop_table('events')
    op.drop_table('equipment')
    # ### end Alembic commands ###
